### ISSUE TITLE
Confusing about the evaluation

### ISSUE THREAD

**Issue by xubenben** [snakeztc/NeuralDialog-CVAE#3]
Hi,

I  recently running your code,  and get this after training with glove,   I find it is confusing that the evaluation has no direct connection with results in your paper.  Could you give a more detailed explain  or  more consist evaluation?

<img width="825" alt="2017-11-16 10 14 26" src="https://user-images.githubusercontent.com/3480189/32870473-ae286254-ca41-11e7-8589-c3455c6a9995.png">

**Comment by snakeztc** [comment]
@xubenben the final evaluation results should be computed against a test dataset with multiple ground truth reference responses. The current code shows not final results since it's only comparing to the test set with 1 reference response.

I recently uploaded the testing dataset with multiple references used in the paper in the data folder. https://github.com/snakeztc/NeuralDialog-CVAE/blob/master/data/test_multi_ref.json. 

You can write a script using the same evaluation function to compute the F1 score against this dataset to obtain the final results.
